# This workflow integrates Scan with GitHub's code scanning feature
# Scan is a free open-source security tool for modern DevOps teams from ShiftLeft
# Visit https://slscan.io/en/latest/integrations/code-scan for help
name: SL Scan

# This section configures the trigger for the workflow. Feel free to customize depending on your convention
on: 
  workflow_dispatch

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  Scan-Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.8
    - name: Android build
      run: |
        chmod +x gradlew
        ./gradlew assembleDebug
    - name: Perform ShiftLeft Scan
      uses: ShiftLeftSecurity/scan-action@master
      env:
        WORKSPACE: ""
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        output: reports
        type: credscan,kotlin
    - uses: actions/upload-artifact@v1
      with:
        name: reports
        path: reports
